###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=taliel

###

GET http://localhost:3000/posts/6762cf989b43b1f08f26c2c6
 
###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello",
    "owner": "taliel",
    "content": "Hello World..."
}

###

GET http://localhost:3000/posts?sender=taliel 

###

PUT http://localhost:3000/posts/ 
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "This is the updated content of the post."
}
//

### 
POST http://localhost:3000/comments
Content-Type: application/json

Body:
{
  "postId": "ObjectId",
  "author": "string",
  "content": "string"
}

### 
GET http://localhost:3000/comments
Response:
[
  {
    "postId": "6762cf989b43b1f08f26c2c6",
    "author": "string",
    "content": "string",
    "createdAt": "timestamp"
  }
]

### 
PUT http://localhost:3000/comments
Content-Type: application/json
Body:
{
  "content": "updated content"
}

### 
DELETE http://localhost:3000/comments
Response:
{
  "message": "Comment deleted successfully"
}
