###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=taliel

###

GET http://localhost:3000/posts/6762cf989b43b1f08f26c2c6
 
###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello",
    "owner": "taliel",
    "content": "Hello World..."
}

###

GET http://localhost:3000/posts?sender=taliel 

###

PUT http://localhost:3000/posts/6762cf989b43b1f08f26c2c6
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "This is the updated content of the post."
}


### 

POST http://localhost:3000/comments
Content-Type: application/json
{
  "postId": "6762cf989b43b1f08f26c2c6",
  "owner": "taliel",
  "content": "This is a comment"
}

### 
GET /comments/post/6762cf989b43b1f08f26c2c6
Response:
[
  {
    "postId": "6762cf989b43b1f08f26c2c6",
    "owner": "taliel",
    "content": "string",
  }
]

### 
PUT /comments/6762cf989b43b1f08f26c2c6
Content-Type: application/json
Body:
{
  "content": "updated content"
}

### 
DELETE /comments/6762cf989b43b1f08f26c2c6
Content-Type: application/json 
{
  "message": "Comment deleted successfully"
}
